blank_issues_enabled: false
contact_links:
  - name: Bug report
    about: Create a report to help us improve
    url: https://github.com/codeforpdx/dwellingly-app/issues/new?template=bug_report.md&labels=bug&projects=codeforpdx/dwellingly-app/4
  - name: Feature request
    about: Suggest an idea for this project
    url: https://github.com/codeforpdx/dwellingly-app/issues/new?template=feature_request.md&projects=codeforpdx/dwellingly-app/4
